import type { CategoryId } from "./category-tree";

export type CatalogRow = {
  slug: string;
  marca: string;
  nombre: string;
  lista: number;
  cash: number | null;
  categoryId: CategoryId;
};

export const catalogRows: CatalogRow[] = [
  { slug: "sieger-derma-x12", marca: "Sieger", nombre: "Derma x12", lista: 96600, cash: 92900, categoryId: "mascota-perro-alimento-dietas" },
  { slug: "sieger-senior-7-x15", marca: "Sieger", nombre: "Senior +7 x15", lista: 106000, cash: 101900, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-lata-medicada", marca: "Sieger", nombre: "Lata medicada", lista: 8700, cash: null, categoryId: "mascota-perro-alimento-dietas" },
  { slug: "sieger-renal-x3", marca: "Sieger", nombre: "Renal x3", lista: 41200, cash: null, categoryId: "mascota-perro-alimento-dietas" },
  { slug: "sieger-gastro-x3", marca: "Sieger", nombre: "Gastro x3", lista: 41200, cash: null, categoryId: "mascota-perro-alimento-dietas" },
  { slug: "sieger-renal-gato-x1-5", marca: "Sieger", nombre: "Renal gato x1,5", lista: 29400, cash: null, categoryId: "mascota-gato-alimento-dietas" },
  { slug: "sieger-gastro-gato-x1-5", marca: "Sieger", nombre: "Gastro gato x1,5", lista: 29400, cash: null, categoryId: "mascota-gato-alimento-dietas" },
  { slug: "sieger-puppy-mini-x1", marca: "Sieger", nombre: "Puppy mini x1", lista: 12900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-puppy-mini-x3", marca: "Sieger", nombre: "Puppy mini x3", lista: 30400, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-puppy-mini-x12", marca: "Sieger", nombre: "Puppy mini x12", lista: 92100, cash: 88500, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-puppy-medium-x1", marca: "Sieger", nombre: "Puppy medium x1", lista: 11800, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-puppy-medium-x3", marca: "Sieger", nombre: "Puppy medium x3", lista: 28900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-puppy-medium-x15", marca: "Sieger", nombre: "Puppy medium x15", lista: 106000, cash: 101900, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-mini-adulto-x1", marca: "Sieger", nombre: "Mini adulto x1", lista: 11900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-mini-adulto-x3", marca: "Sieger", nombre: "Mini adulto x3", lista: 28400, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-mini-adulto-x12", marca: "Sieger", nombre: "Mini adulto x12", lista: 84700, cash: 81900, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-adulto-medium-x3", marca: "Sieger", nombre: "Adulto medium x3", lista: 27600, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-adulto-medium-x15", marca: "Sieger", nombre: "Adulto medium x15", lista: 97300, cash: 93500, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-senior-x1", marca: "Sieger", nombre: "Senior x1", lista: 12900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-senior-x3", marca: "Sieger", nombre: "Senior x3", lista: 29500, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-senior-mini-x12", marca: "Sieger", nombre: "Senior mini x12", lista: 92000, cash: 88500, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-reduced-calorias-x3", marca: "Sieger", nombre: "Reduced calorías x3", lista: 28400, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-reduced-calorias-x12", marca: "Sieger", nombre: "Reduced calorías x12", lista: 83200, cash: 79900, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-derma-x3", marca: "Sieger", nombre: "Derma x3", lista: 32400, cash: null, categoryId: "mascota-perro-alimento-dietas" },
  { slug: "sieger-criadores-x20", marca: "Sieger", nombre: "Criadores x20", lista: 106500, cash: 93000, categoryId: "mascota-perro-alimento-seco" },
  { slug: "sieger-kitten-x1", marca: "Sieger", nombre: "Kitten x1", lista: 18000, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "sieger-urinary-x1", marca: "Sieger", nombre: "Urinary x1", lista: 18000, cash: null, categoryId: "mascota-gato-alimento-dietas" },
  { slug: "sieger-sterilized-x1", marca: "Sieger", nombre: "Sterilized x1", lista: 18000, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "sieger-adulto-gato-x1", marca: "Sieger", nombre: "Adulto gato x1", lista: 18000, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "sieger-gato-x10", marca: "Sieger", nombre: "Gato x10", lista: 118000, cash: 112000, categoryId: "mascota-gato-alimento-seco" },
  { slug: "sieger-pouch-perro", marca: "Sieger", nombre: "Pouch perro", lista: 3500, cash: null, categoryId: "mascota-perro-alimento-humedo" },
  { slug: "sieger-pouch-gato", marca: "Sieger", nombre: "Pouch gato", lista: 4000, cash: null, categoryId: "mascota-gato-alimento-humedo" },
  { slug: "sieger-pouch-recovery", marca: "Sieger", nombre: "Pouch recovery", lista: 4200, cash: null, categoryId: "mascota-perro-alimento-humedo" },
  { slug: "sieger-lata-gato", marca: "Sieger", nombre: "Lata gato", lista: 7400, cash: null, categoryId: "mascota-gato-alimento-humedo" },
  { slug: "sieger-lata-recovery", marca: "Sieger", nombre: "Lata recovery", lista: 7800, cash: null, categoryId: "mascota-perro-alimento-humedo" },
  { slug: "sieger-lata-perro", marca: "Sieger", nombre: "Lata perro", lista: 7200, cash: null, categoryId: "mascota-perro-alimento-humedo" },
  { slug: "maxxium-lata-gato-grande", marca: "Maxxium", nombre: "Lata gato (grande)", lista: 6200, cash: null, categoryId: "mascota-gato-alimento-humedo" },
  { slug: "maxxium-lata-gato-chica", marca: "Maxxium", nombre: "Lata gato (chica)", lista: 3000, cash: null, categoryId: "mascota-gato-alimento-humedo" },
  { slug: "maxxium-cachorro-x3", marca: "Maxxium", nombre: "Cachorro x3", lista: 20500, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "maxxium-cachorro-x20", marca: "Maxxium", nombre: "Cachorro x20", lista: 96900, cash: 93200, categoryId: "mascota-perro-alimento-seco" },
  { slug: "maxxium-cordero-x15", marca: "Maxxium", nombre: "Cordero x15", lista: 89800, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "maxxium-cordero-x3", marca: "Maxxium", nombre: "Cordero x3", lista: 25700, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "maxxium-adulto-x3", marca: "Maxxium", nombre: "Adulto x3", lista: 19500, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "maxxium-gato-x1", marca: "Maxxium", nombre: "Gato x1", lista: 13600, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "maxxium-adulto-x20", marca: "Maxxium", nombre: "Adulto x20", lista: 88300, cash: 77200, categoryId: "mascota-perro-alimento-seco" },
  { slug: "agility-reduced-x3", marca: "Agility", nombre: "Reduced x3", lista: 22100, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "agility-cachorro-x3", marca: "Agility", nombre: "Cachorro x3", lista: 19600, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "agility-cachorro-x20", marca: "Agility", nombre: "Cachorro x20", lista: 87400, cash: 83900, categoryId: "mascota-perro-alimento-seco" },
  { slug: "agility-adulto-x3", marca: "Agility", nombre: "Adulto x3", lista: 16900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "agility-adulto-x20", marca: "Agility", nombre: "Adulto x20", lista: 74400, cash: 64900, categoryId: "mascota-perro-alimento-seco" },
  { slug: "agility-cordero-x3", marca: "Agility", nombre: "Cordero x3", lista: 22100, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "agility-cordero-x15", marca: "Agility", nombre: "Cordero x15", lista: 78400, cash: 75400, categoryId: "mascota-perro-alimento-seco" },
  { slug: "agility-adulto-raza-peq-x1-5", marca: "Agility", nombre: "Adulto raza peq x1,5", lista: 10600, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "agility-adulto-raza-peq-x15", marca: "Agility", nombre: "Adulto raza peq x15", lista: 69900, cash: 67200, categoryId: "mascota-perro-alimento-seco" },
  { slug: "agility-derma-x3", marca: "Agility", nombre: "Derma x3", lista: 20700, cash: null, categoryId: "mascota-perro-alimento-dietas" },
  { slug: "agility-kitten-x1-5", marca: "Agility", nombre: "Kitten x1,5", lista: 17300, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "agility-kitten-x10", marca: "Agility", nombre: "Kitten x10", lista: 80300, cash: 77200, categoryId: "mascota-gato-alimento-seco" },
  { slug: "agility-gato-adulto-x1-5", marca: "Agility", nombre: "Gato adulto x1,5", lista: 16000, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "agility-gato-adulto-x10", marca: "Agility", nombre: "Gato adulto x10", lista: 75000, cash: 68300, categoryId: "mascota-gato-alimento-seco" },
  { slug: "agility-control-de-peso-x1-5", marca: "Agility", nombre: "Control de peso x1,5", lista: 18600, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "agility-urinary-x1-5", marca: "Agility", nombre: "Urinary x1,5", lista: 17300, cash: null, categoryId: "mascota-gato-alimento-dietas" },
  { slug: "agility-urinary-x10", marca: "Agility", nombre: "Urinary x10", lista: 80300, cash: 73000, categoryId: "mascota-gato-alimento-dietas" },
  { slug: "agility-salmon-x1-5", marca: "Agility", nombre: "Salmon x1,5", lista: 18100, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "agility-senior-7-x15", marca: "Agility", nombre: "Senior +7 x15", lista: 71700, cash: 69000, categoryId: "mascota-perro-alimento-seco" },
  { slug: "agility-derma-x15", marca: "Agility", nombre: "Derma x15", lista: 73100, cash: 70300, categoryId: "mascota-perro-alimento-dietas" },
  { slug: "agility-lata", marca: "Agility", nombre: "Lata", lista: 5500, cash: null, categoryId: "mascota-perro-alimento-humedo" },
  { slug: "7-vida-adulto-x1", marca: "7 Vida", nombre: "Adulto x1", lista: 8700, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "7-vida-adulto-x10", marca: "7 Vida", nombre: "Adulto x10", lista: 57900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "nutricare-adulto-x20", marca: "Nutricare", nombre: "Adulto x20", lista: 49400, cash: 44000, categoryId: "mascota-perro-alimento-seco" },
  { slug: "nutricare-adulto-x7-5", marca: "Nutricare", nombre: "Adulto x7,5", lista: 19400, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "nutricare-cachorro-x15", marca: "Nutricare", nombre: "Cachorro x15", lista: 40800, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "nutricare-adulto-x3", marca: "Nutricare", nombre: "Adulto x3", lista: 14000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "smug-adulto-x20", marca: "Smug", nombre: "Adulto x20", lista: 27300, cash: 25500, categoryId: "mascota-perro-alimento-seco" },
  { slug: "smug-adulto-x10", marca: "Smug", nombre: "Adulto x10", lista: 16000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "bocato-adulto-x20", marca: "Bocato", nombre: "Adulto x20", lista: 32700, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "bocato-adulto-x10", marca: "Bocato", nombre: "Adulto x10", lista: 18900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "bocato-cachorro-x10", marca: "Bocato", nombre: "Cachorro x10", lista: 21000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "bocato-gato-x10", marca: "Bocato", nombre: "Gato x10", lista: 23200, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "maxi-cat-gato-x10", marca: "Maxi Cat", nombre: "Gato x10", lista: 23300, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "old-prince-kitten-cordero-x3", marca: "Old Prince", nombre: "Kitten cordero x3", lista: 27300, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "old-prince-gato-cordero-x3", marca: "Old Prince", nombre: "Gato cordero x3", lista: 35700, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "old-prince-gato-esterilizado-x3", marca: "Old Prince", nombre: "Gato esterilizado x3", lista: 26200, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "old-prince-gato-urinary-x3", marca: "Old Prince", nombre: "Gato urinary x3", lista: 27300, cash: null, categoryId: "mascota-gato-alimento-dietas" },
  { slug: "old-prince-gato-premium-x3", marca: "Old Prince", nombre: "Gato premium x3", lista: 23800, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "old-prince-puppy-medium-x3", marca: "Old Prince", nombre: "Puppy medium x3", lista: 15700, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "old-prince-adulto-medium-x3", marca: "Old Prince", nombre: "Adulto medium x3", lista: 14800, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "old-prince-cordero-x15", marca: "Old Prince", nombre: "Cordero x15", lista: 66850, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "old-prince-cordero-x3", marca: "Old Prince", nombre: "Cordero x3", lista: 19400, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "old-prince-puppy-pequena-x3", marca: "Old Prince", nombre: "Puppy pequeña x3", lista: 17000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "old-prince-adulto-pequena-x3", marca: "Old Prince", nombre: "Adulto pequeña x3", lista: 16000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "old-prince-adulto-rp-x7-5", marca: "Old Prince", nombre: "Adulto RP x7,5", lista: 33700, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "old-prince-cachorro-rp-x7-5", marca: "Old Prince", nombre: "Cachorro RP x7,5", lista: 34800, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "optimun-kitten-x1", marca: "Optimun", nombre: "Kitten x1", lista: 12300, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "optimun-gato-x3", marca: "Optimun", nombre: "Gato x3", lista: 28900, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "optimun-castrado-x3", marca: "Optimun", nombre: "Castrado x3", lista: 29900, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "optimun-cachorro-x3", marca: "Optimun", nombre: "Cachorro x3", lista: 19900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "optimun-adulto-x3", marca: "Optimun", nombre: "Adulto x3", lista: 18200, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "eukanuba-fit-body-small-x3", marca: "Eukanuba", nombre: "Fit body small x3", lista: 29900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "eukanuba-fit-body-medium-x3", marca: "Eukanuba", nombre: "Fit body medium x3", lista: 29300, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "eukanuba-senior-x3", marca: "Eukanuba", nombre: "Senior x3", lista: 28900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "eukanuba-puppy-small-x1", marca: "Eukanuba", nombre: "Puppy small x1", lista: 10900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "eukanuba-puppy-small-medium-large-x3", marca: "Eukanuba", nombre: "Puppy small/medium/large x3", lista: 28000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "eukanuba-adulto-small-x1", marca: "Eukanuba", nombre: "Adulto small x1", lista: 10400, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "eukanuba-adulto-small-medium-large-x3", marca: "Eukanuba", nombre: "Adulto small/medium/large x3", lista: 27100, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "eukanuba-gato-x1-5", marca: "Eukanuba", nombre: "Gato x1,5", lista: 20100, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "eukanuba-kitten-x1-5", marca: "Eukanuba", nombre: "Kitten x1,5", lista: 15300, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "eukanuba-gato-x3", marca: "Eukanuba", nombre: "Gato x3", lista: 38300, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "eukanuba-kitten-x3", marca: "Eukanuba", nombre: "Kitten x3", lista: 39600, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "eukanuba-adulto-x15", marca: "Eukanuba", nombre: "Adulto x15", lista: 98400, cash: 94000, categoryId: "mascota-perro-alimento-seco" },
  { slug: "eukanuba-cachorro-x15", marca: "Eukanuba", nombre: "Cachorro x15", lista: 99300, cash: 95000, categoryId: "mascota-perro-alimento-seco" },
  { slug: "pedigree-pouch", marca: "Pedigree", nombre: "Pouch", lista: 1300, cash: null, categoryId: "mascota-perro-alimento-humedo" },
  { slug: "pedigree-lata", marca: "Pedigree", nombre: "Lata", lista: 3800, cash: null, categoryId: "mascota-perro-alimento-humedo" },
  { slug: "pedigree-cachorro-x8", marca: "Pedigree", nombre: "Cachorro x8", lista: 33000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "pedigree-cachorro-x21", marca: "Pedigree", nombre: "Cachorro x21", lista: 75500, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "pedigree-adulto-x8", marca: "Pedigree", nombre: "Adulto x8", lista: 31400, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "pedigree-adulto-x21", marca: "Pedigree", nombre: "Adulto x21", lista: 69900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "pedigree-adulto-raz-peq-x8", marca: "Pedigree", nombre: "Adulto raz. peq. x8", lista: 31400, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "pedigree-adulto-x15", marca: "Pedigree", nombre: "Adulto x15", lista: 57200, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "pedigree-adulto-raz-peq-x15", marca: "Pedigree", nombre: "Adulto raz. peq. x15", lista: 57200, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "pedigree-adulto-rp-x21", marca: "Pedigree", nombre: "Adulto RP x21", lista: 80600, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "pedigree-senior-x8", marca: "Pedigree", nombre: "Senior x8", lista: 29200, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "pedigree-dentastix-x1", marca: "Pedigree", nombre: "Dentastix x1", lista: 1500, cash: null, categoryId: "mascota-perro-alimento-snacks" },
  { slug: "pedigree-dentastix-x3", marca: "Pedigree", nombre: "Dentastix x3", lista: 3600, cash: null, categoryId: "mascota-perro-alimento-snacks" },
  { slug: "pedigree-dentastix-x7", marca: "Pedigree", nombre: "Dentastix x7", lista: 6900, cash: null, categoryId: "mascota-perro-alimento-snacks" },
  { slug: "pedigree-rodeo", marca: "Pedigree", nombre: "Rodeo", lista: 2500, cash: null, categoryId: "mascota-perro-alimento-snacks" },
  { slug: "pedigree-biscrok-chico", marca: "Pedigree", nombre: "Biscrok chico", lista: 2500, cash: null, categoryId: "mascota-perro-alimento-snacks" },
  { slug: "pedigree-biscrok-grande", marca: "Pedigree", nombre: "Biscrok grande", lista: 7500, cash: null, categoryId: "mascota-perro-alimento-snacks" },
  { slug: "whiskas-sobre", marca: "Whiskas", nombre: "Sobre", lista: 1300, cash: null, categoryId: "mascota-gato-alimento-humedo" },
  { slug: "whiskas-lata", marca: "Whiskas", nombre: "Lata", lista: 3800, cash: null, categoryId: "mascota-gato-alimento-humedo" },
  { slug: "whiskas-gato-x10", marca: "Whiskas", nombre: "Gato x10", lista: 55400, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "whiskas-snack-chico-40gr", marca: "Whiskas", nombre: "Snack chico 40gr", lista: 2700, cash: null, categoryId: "mascota-gato-alimento-snacks" },
  { slug: "whiskas-snack-grande-80gr", marca: "Whiskas", nombre: "Snack grande 80gr", lista: 3200, cash: null, categoryId: "mascota-gato-alimento-snacks" },
  { slug: "pampa-adulto-rp-x15", marca: "Pampa", nombre: "Adulto RP x15", lista: 39900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "voraz-adulto-x20", marca: "Voraz", nombre: "Adulto x20", lista: 28700, cash: 25300, categoryId: "mascota-perro-alimento-seco" },
  { slug: "voraz-adulto-x10", marca: "Voraz", nombre: "Adulto x10", lista: 15800, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "maintenance-adulto-rp-x15", marca: "Maintenance", nombre: "Adulto RP x15", lista: 29700, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "maintenance-adulto-x22", marca: "Maintenance", nombre: "Adulto x22", lista: 39900, cash: 36300, categoryId: "mascota-perro-alimento-seco" },
  { slug: "company-gato-x3", marca: "Company", nombre: "Gato x3", lista: 16000, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "company-kitten-x3", marca: "Company", nombre: "Kitten x3", lista: 17000, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "livra-gato-x3", marca: "Livra", nombre: "Gato x3", lista: 28900, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "livra-cachorro-x3", marca: "Livra", nombre: "Cachorro x3", lista: 24000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "livra-adulto-x3", marca: "Livra", nombre: "Adulto x3", lista: 22000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "royal-canin-adulto-xs-x1", marca: "Royal Canin", nombre: "Adulto XS x1", lista: 17100, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "royal-canin-baby-cat-x1-5", marca: "Royal Canin", nombre: "Baby cat x1,5", lista: 39500, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "royal-canin-urinary-perro-x1-5", marca: "Royal Canin", nombre: "Urinary perro x1,5", lista: 38900, cash: null, categoryId: "mascota-perro-alimento-dietas" },
  { slug: "royal-canin-hypoallergenic-x2", marca: "Royal Canin", nombre: "Hypoallergenic x2", lista: 45100, cash: null, categoryId: "mascota-perro-alimento-dietas" },
  { slug: "royal-canin-kitten-x1-5", marca: "Royal Canin", nombre: "Kitten x1,5", lista: 37600, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "royal-canin-indoor-x1-5", marca: "Royal Canin", nombre: "Indoor x1,5", lista: 35200, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "royal-canin-indoor-7-x1-5", marca: "Royal Canin", nombre: "Indoor +7 x1,5", lista: 37000, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "royal-canin-active-gato-x1-5", marca: "Royal Canin", nombre: "Active gato x1,5", lista: 37000, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "royal-canin-fit-32-x1-5", marca: "Royal Canin", nombre: "Fit 32 x1,5", lista: 33000, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "royal-canin-urinary-gato-x1-5", marca: "Royal Canin", nombre: "Urinary gato x1,5", lista: 43800, cash: null, categoryId: "mascota-gato-alimento-dietas" },
  { slug: "royal-canin-mini-starter-x1", marca: "Royal Canin", nombre: "Mini starter x1", lista: 17800, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "royal-canin-mini-starter-x3", marca: "Royal Canin", nombre: "Mini starter x3", lista: 48100, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "royal-canin-mini-puppy-x1", marca: "Royal Canin", nombre: "Mini puppy x1", lista: 16500, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "royal-canin-mini-puppy-x3", marca: "Royal Canin", nombre: "Mini puppy x3", lista: 44800, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "royal-canin-mini-adulto-x1", marca: "Royal Canin", nombre: "Mini adulto x1", lista: 16500, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "royal-canin-mini-adult-x3", marca: "Royal Canin", nombre: "Mini adult x3", lista: 43000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "royal-canin-mini-adulto-8-x3", marca: "Royal Canin", nombre: "Mini adulto +8 x3", lista: 45800, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "royal-canin-adulto-mini-12-x3", marca: "Royal Canin", nombre: "Adulto mini +12 x3", lista: 45800, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "royal-canin-pouch-puppy", marca: "Royal Canin", nombre: "Pouch puppy", lista: 2700, cash: null, categoryId: "mascota-perro-alimento-humedo" },
  { slug: "royal-canin-pouch-adulto", marca: "Royal Canin", nombre: "Pouch adulto", lista: 2700, cash: null, categoryId: "mascota-perro-alimento-humedo" },
  { slug: "royal-canin-pouch-kitten", marca: "Royal Canin", nombre: "Pouch kitten", lista: 3800, cash: null, categoryId: "mascota-gato-alimento-humedo" },
  { slug: "royal-canin-pouch-urinary", marca: "Royal Canin", nombre: "Pouch urinary", lista: 3800, cash: null, categoryId: "mascota-gato-alimento-humedo" },
  { slug: "royal-canin-recovery", marca: "Royal Canin", nombre: "Recovery", lista: 8900, cash: null, categoryId: "mascota-perro-alimento-humedo" },
  { slug: "royal-canin-renal-perro-x2", marca: "Royal Canin", nombre: "Renal perro x2", lista: 25400, cash: null, categoryId: "mascota-perro-alimento-dietas" },
  { slug: "royal-canin-mobily-x2", marca: "Royal Canin", nombre: "Mobily x2", lista: 42400, cash: null, categoryId: "mascota-perro-alimento-dietas" },
  { slug: "royal-canin-cardiac-x2", marca: "Royal Canin", nombre: "Cardiac x2", lista: 42300, cash: null, categoryId: "mascota-perro-alimento-dietas" },
  { slug: "royal-canin-gastro-x2", marca: "Royal Canin", nombre: "Gastro x2", lista: 36700, cash: null, categoryId: "mascota-perro-alimento-dietas" },
  { slug: "royal-canin-hepatic-gato-x2", marca: "Royal Canin", nombre: "Hepatic gato x2", lista: 42500, cash: null, categoryId: "mascota-gato-alimento-dietas" },
  { slug: "royal-canin-renal-gato-x2", marca: "Royal Canin", nombre: "Renal gato x2", lista: 49800, cash: null, categoryId: "mascota-gato-alimento-dietas" },
  { slug: "royal-canin-gastro-gato-x2", marca: "Royal Canin", nombre: "Gastro gato x2", lista: 54400, cash: null, categoryId: "mascota-gato-alimento-dietas" },
  { slug: "royal-canin-maxi-adulto-x15", marca: "Royal Canin", nombre: "Maxi adulto x15", lista: 154600, cash: 140000, categoryId: "mascota-perro-alimento-seco" },
  { slug: "royal-canin-mini-puppy-x7-5", marca: "Royal Canin", nombre: "Mini puppy x7,5", lista: 90300, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "royal-canin-mini-adulto-x7-5", marca: "Royal Canin", nombre: "Mini adulto x7,5", lista: 99600, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "excellent-gato-x1", marca: "Excellent", nombre: "Gato x1", lista: 13400, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "excellent-steriliced-x1", marca: "Excellent", nombre: "Steriliced x1", lista: 15600, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "excellent-kitten-x1", marca: "Excellent", nombre: "Kitten x1", lista: 14800, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "excellent-urinary-x1", marca: "Excellent", nombre: "Urinary x1", lista: 15600, cash: null, categoryId: "mascota-gato-alimento-dietas" },
  { slug: "excellent-adulto-perro-x1", marca: "Excellent", nombre: "Adulto perro x1", lista: 8500, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "excellent-puppy-x1", marca: "Excellent", nombre: "Puppy x1", lista: 9400, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "excellent-gato-x3", marca: "Excellent", nombre: "Gato x3", lista: 34500, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "excellent-gato-x7-5", marca: "Excellent", nombre: "Gato x7,5", lista: 73120, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "excellent-adulto-mantenimiento-x20", marca: "Excellent", nombre: "Adulto mantenimiento x20", lista: 72600, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "excellent-urinary-x7-5", marca: "Excellent", nombre: "Urinary x7,5", lista: 84300, cash: null, categoryId: "mascota-gato-alimento-dietas" },
  { slug: "excellent-kitten-x7-5", marca: "Excellent", nombre: "Kitten x7,5", lista: 80900, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "excellent-steriliced-x7-5", marca: "Excellent", nombre: "Steriliced x7,5", lista: 84300, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "excellent-adulto-small-x3", marca: "Excellent", nombre: "Adulto small x3", lista: 23300, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "excellent-puppy-small-x3", marca: "Excellent", nombre: "Puppy small x3", lista: 25400, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "dog-chow-adulto-x21", marca: "Dog Chow", nombre: "Adulto x21", lista: 71400, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "dogui-adulto-x21", marca: "Dogui", nombre: "Adulto x21", lista: 49600, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "capitan-adulto-x22", marca: "Capitan", nombre: "Adulto x22", lista: 29300, cash: 22500, categoryId: "mascota-perro-alimento-seco" },
  { slug: "capitan-gato-x10", marca: "Capitan", nombre: "Gato x10", lista: 22700, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "dog-prince-adulto-x15", marca: "Dog Prince", nombre: "Adulto x15", lista: 19900, cash: 18000, categoryId: "mascota-perro-alimento-seco" },
  { slug: "dog-prince-adulto-x22", marca: "Dog Prince", nombre: "Adulto x22", lista: 28900, cash: 26400, categoryId: "mascota-perro-alimento-seco" },
  { slug: "zimpi-adulto-x25", marca: "Zimpi", nombre: "Adulto x25", lista: 31900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "ganacan-adulto-x25", marca: "Ganacan", nombre: "Adulto x25", lista: 36300, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "amici-gato-x10", marca: "Amici", nombre: "Gato x10", lista: 29000, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "zimpi-gato-x10", marca: "Zimpi", nombre: "Gato x10", lista: 25000, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "ganacat-gato-x10", marca: "Ganacat", nombre: "Gato x10", lista: 28300, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "odwalla-adulto-x25", marca: "Odwalla", nombre: "Adulto x25", lista: 47900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "has-cachorro-x10", marca: "HAS", nombre: "Cachorro x10", lista: 25100, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "has-criadores-x20", marca: "HAS", nombre: "Criadores x20", lista: 31200, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "has-premium-x20", marca: "HAS", nombre: "Premium x20", lista: 42600, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "has-gato-x10", marca: "HAS", nombre: "Gato x10", lista: 24800, cash: null, categoryId: "mascota-gato-alimento-seco" },
  { slug: "biohas-adulto-x20", marca: "Biohas", nombre: "Adulto x20", lista: 37000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "chasque-adulto-x20", marca: "Chasque", nombre: "Adulto x20", lista: 32900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "tigre-adulto-x22", marca: "Tigre", nombre: "Adulto x22", lista: 32900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "rey-can-adulto-x22", marca: "Rey Can", nombre: "Adulto x22", lista: 42900, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "rey-can-rp-x15", marca: "Rey Can", nombre: "RP x15", lista: 30200, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "rey-can-rp-x8", marca: "Rey Can", nombre: "RP x8", lista: 17000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "simpli-adulto-x22", marca: "Simpli", nombre: "Adulto x22", lista: 34400, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "gandum-adulto-x20", marca: "Gandum", nombre: "Adulto x20", lista: 22100, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "puppy-food-adulto-x20", marca: "Puppy Food", nombre: "Adulto x20", lista: 36600, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "upper-urinary-x1-5", marca: "Upper", nombre: "Urinary x1,5", lista: 19900, cash: 14900, categoryId: "mascota-perro-alimento-seco" },
  { slug: "upper-castrado-x1-5", marca: "Upper", nombre: "Castrado x1,5", lista: 19900, cash: 14900, categoryId: "mascota-perro-alimento-seco" },
  { slug: "misterper-adulto-x20", marca: "Misterper", nombre: "Adulto x20", lista: 49900, cash: 45500, categoryId: "mascota-perro-alimento-seco" },
  { slug: "biopet-adulto-x20", marca: "Biopet", nombre: "Adulto x20", lista: 37000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "estampa-adulto-x20", marca: "Estampa", nombre: "Adulto x20", lista: 48700, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "estampa-cachorro-x15", marca: "Estampa", nombre: "Cachorro x15", lista: 52500, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "estampa-adulto-rp-x15", marca: "Estampa", nombre: "Adulto RP x15", lista: 49800, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "gati-x8", marca: "Gati", nombre: "x8", lista: 32000, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "gati-x15", marca: "Gati", nombre: "x15", lista: 53800, cash: null, categoryId: "mascota-perro-alimento-seco" },
  { slug: "total-khan-adulto-x20", marca: "Total Khan", nombre: "Adulto x20", lista: 39900, cash: 35000, categoryId: "mascota-perro-alimento-seco" },
  { slug: "accesorios-viruta", marca: "Accesorios", nombre: "Viruta", lista: 4000, cash: null, categoryId: "general-accesorios-literas" },
  { slug: "accesorios-litera-chica", marca: "Accesorios", nombre: "Litera chica", lista: 6500, cash: null, categoryId: "general-accesorios-literas" },
  { slug: "accesorios-litera-mediana", marca: "Accesorios", nombre: "Litera mediana", lista: 8300, cash: null, categoryId: "general-accesorios-literas" },
  { slug: "accesorios-litera-grande", marca: "Accesorios", nombre: "Litera grande", lista: 15400, cash: null, categoryId: "general-accesorios-literas" },
  { slug: "accesorios-kit-litera", marca: "Accesorios", nombre: "Kit litera", lista: 12200, cash: null, categoryId: "general-accesorios-literas" },
  { slug: "accesorios-bombacha-higienica-negra", marca: "Accesorios", nombre: "Bombacha higiénica negra", lista: 14800, cash: null, categoryId: "general-accesorios-bombachas" },
  { slug: "accesorios-bombacha-con-puntilla", marca: "Accesorios", nombre: "Bombacha con puntilla", lista: 16700, cash: null, categoryId: "general-accesorios-bombachas" },
  { slug: "accesorios-bozal-rejilla-talle-1", marca: "Accesorios", nombre: "Bozal rejilla talle 1", lista: 8800, cash: null, categoryId: "general-accesorios-bozales" },
  { slug: "accesorios-bozal-rejilla-talle-2", marca: "Accesorios", nombre: "Bozal rejilla talle 2", lista: 8800, cash: null, categoryId: "general-accesorios-bozales" },
  { slug: "accesorios-bozal-rejilla-talle-3", marca: "Accesorios", nombre: "Bozal rejilla talle 3", lista: 8800, cash: null, categoryId: "general-accesorios-bozales" },
  { slug: "accesorios-bozal-rejilla-talle-4", marca: "Accesorios", nombre: "Bozal rejilla talle 4", lista: 10500, cash: null, categoryId: "general-accesorios-bozales" },
  { slug: "accesorios-bozal-rejilla-talle-5", marca: "Accesorios", nombre: "Bozal rejilla talle 5", lista: 10500, cash: null, categoryId: "general-accesorios-bozales" },
  { slug: "accesorios-bozal-rejilla-talle-6", marca: "Accesorios", nombre: "Bozal rejilla talle 6", lista: 15400, cash: null, categoryId: "general-accesorios-bozales" },
  { slug: "accesorios-bozal-rejilla-talle-7", marca: "Accesorios", nombre: "Bozal rejilla talle 7", lista: 15400, cash: null, categoryId: "general-accesorios-bozales" },
  { slug: "accesorios-bozal-nylon", marca: "Accesorios", nombre: "Bozal nylon", lista: 13000, cash: null, categoryId: "general-accesorios-bozales" },
  { slug: "accesorios-bozal-silicona", marca: "Accesorios", nombre: "Bozal silicona", lista: 42500, cash: null, categoryId: "general-accesorios-bozales" },
  { slug: "accesorios-bozal-cuero", marca: "Accesorios", nombre: "Bozal cuero", lista: 18000, cash: null, categoryId: "general-accesorios-bozales" },
  { slug: "collares-collar-simple-talle-12", marca: "Collares", nombre: "Collar simple · talle 12", lista: 2900, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-simple-talle-10", marca: "Collares", nombre: "Collar simple · talle 10", lista: 3000, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-simple-talle-8", marca: "Collares", nombre: "Collar simple · talle 8", lista: 4000, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-simple-talle-6", marca: "Collares", nombre: "Collar simple · talle 6", lista: 5500, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-simple-talle-4", marca: "Collares", nombre: "Collar simple · talle 4", lista: 5800, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-simple-talle-3", marca: "Collares", nombre: "Collar simple · talle 3", lista: 6600, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-simple-talle-2", marca: "Collares", nombre: "Collar simple · talle 2", lista: 6800, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-simple-talle-1", marca: "Collares", nombre: "Collar simple · talle 1", lista: 7000, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-doble-talle-5", marca: "Collares", nombre: "Collar doble · talle 5", lista: 8300, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-doble-talle-4", marca: "Collares", nombre: "Collar doble · talle 4", lista: 10900, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-doble-talle-3", marca: "Collares", nombre: "Collar doble · talle 3", lista: 10900, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-doble-talle-2", marca: "Collares", nombre: "Collar doble · talle 2", lista: 11200, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-doble-talle-1", marca: "Collares", nombre: "Collar doble · talle 1", lista: 11500, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-doble-talle-0", marca: "Collares", nombre: "Collar doble · talle 0", lista: 12100, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-nato-talle-30-mm", marca: "Collares", nombre: "Collar NATO · talle 30 mm", lista: 21000, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-nato-talle-40-mm", marca: "Collares", nombre: "Collar NATO · talle 40 mm", lista: 22500, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-collar-nato-talle-60-mm", marca: "Collares", nombre: "Collar NATO · talle 60 mm", lista: 24500, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-nato-con-broche-talle", marca: "Collares", nombre: "NATO con broche · talle —", lista: 18900, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-correa-sola-talle-chica", marca: "Collares", nombre: "Correa sola · talle chica", lista: 9900, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-correa-sola-talle-mediana", marca: "Collares", nombre: "Correa sola · talle mediana", lista: 13900, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "collares-correa-sola-talle-grande", marca: "Collares", nombre: "Correa sola · talle grande", lista: 15400, cash: null, categoryId: "general-accesorios-collares-correas" },
  { slug: "ropa-polar-perro-talles-1-12-desde-6-000-a-15-700-segun-talle", marca: "Ropa", nombre: "Polar perro · talles 1–12 (desde $6.000 a $15.700 según talle)", lista: 6000, cash: null, categoryId: "general-ropa" },
  { slug: "ropa-plush-con-corderito-talles-25-85-desde-13-500-a-43-900", marca: "Ropa", nombre: "Plush con corderito · talles 25–85 (desde $13.500 a $43.900)", lista: 13500, cash: null, categoryId: "general-ropa" },
  { slug: "ropa-soft-plus-talles-0-6-desde-13-000-a-20-000", marca: "Ropa", nombre: "Soft Plus · talles 0–6 (desde $13.000 a $20.000)", lista: 13000, cash: null, categoryId: "general-ropa" },
  { slug: "ropa-matelase-talles-2-10-desde-14-000-a-39-000", marca: "Ropa", nombre: "Matelasé · talles 2–10 (desde $14.000 a $39.000)", lista: 14000, cash: null, categoryId: "general-ropa" },
];
